name: MY First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - name: Print Hello World
        run: |
          echo "Hello World! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Love this feature! :medal_sports:" >> $GITHUB_STEP_SUMMARY

          job_1:
            runs-on: ubuntu-latest
            steps:
              -  run: "echo Job: ${{ github}}"
          
         job_2:
            runs-on: ubuntu-latest
            needs:job_1:
            steps:
              -  run: "echo Job: ${{ github}}"
              
                 job_3:
            runs-on: ubuntu-latest
            needs: job_1
            steps:
              -  run: "echo Job: ${{ github}}"
              
